version: '3.8'

services:

  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - .:/application
    ports:
      - "5001:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6001:6379"
    volumes:
      - redis-data:/data

  app:
    build: .
    working_dir: /application/server
    env_file:
      - .env
    command: "tail -f /dev/null"
    #     command: ["python", "manage.py", "runserver", "0:9001"]
    volumes:
      - .:/application
      - app-python-site-packages:/usr/local/lib/python3.8/site-packages
      - app-usr-local-bin:/usr/local/bin
    ports:
      - "9001:9001"
    depends_on:
      - db
      - redis


volumes:
  app-python-site-packages:
    driver: local
  postgres-data:
    driver: local
  app-usr-local-bin:
    driver: local
  redis-data:
    driver: local


